### ISSUE TITLE
Color highlighting instead of icons

### ISSUE THREAD

**Issue by roman-holovin** [Xuyuanp/nerdtree-git-plugin#15]
Can this be implemented?

**Comment by Xuyuanp** [comment]
Good idea! But a little hard...

**Comment by sekjun9878** [comment]
+1

**Comment by agauniyal** [comment]
+1

**Comment by adinvadim** [comment]
+1

**Comment by KabbAmine** [comment]
:+1:

**Comment by marionebl** [comment]
:+1:

**Comment by charlydagos** [comment]
+1

**Comment by robinfehr** [comment]
+1 quickly had a look - the api provided by nerdtree and the underlying highlight does rly not make it easier 🍶

**Comment by 0x00A** [comment]
@Xuyuanp what about using various zero-width unicode characters to determine the colors?

**Comment by robinfehr** [comment]
@0x00A Cool idea that could actually work - setting the flag with the vim's nr2char({expr}[, {utf8}]) function  and expand the match for each group could work out. I'm gonna try that the next week.

**Comment by Xuyuanp** [comment]
@0x00A Good idea!

@robinfehr Thank you! Waiting for your good news.

**Comment by robinfehr** [comment]
tried it - works like a charm. will implement a useful approach and upload it asap.

**Comment by Xuyuanp** [comment]
@robinfehr Awesome! 

And how could you display the folder icon?

**Comment by KabbAmine** [comment]
> And how could you display the folder icon?

https://github.com/ryanoasis/vim-devicons

**Comment by robinfehr** [comment]
assuming you're using the vim-devicons with a nerd font that contains the symbol then add this:
```
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
```
my font: Inconsolata for Powerline Nerd Font Complete

**Comment by Xuyuanp** [comment]
Got it. Thank you @robinfehr @KabbAmine

**Comment by robinfehr** [comment]
btw. in a second step we should improve the logic for the git status "untracked" and add a flag to nodes below a node marked as "untracked".

**Comment by robinfehr** [comment]
second step is implemented too now ;)

**Comment by robinfehr** [comment]
@Xuyuanp can you please verify if the 

`git status --short `

of a staged file really returns 

> [MAC] 

I cant rly see second flags when i add the short format param

**Comment by robinfehr** [comment]
@Xuyuanp What do you think - should we show the difference between staged and unstaged (atom plugin for example makes no difference) ? if we want to show the difference then we might need to add either a flag or a new colour because you still want to know the state like "modified" next to the staged flag.

**Comment by Xuyuanp** [comment]
@robinfehr I think that "untracked" and "added" are definitely diff status.

And "modified" after 'staged' status is diff from both 'staged' and 'modified' indeed, I saw this situation on the beginning, but I finally treated them same to void making it too complicated.

**Comment by 0x00A** [comment]
Any status on this? It would be awesome to close this issue :D

**Comment by 0x00A** [comment]
^bump

**Comment by robinfehr** [comment]
@0x00A feel free to work/use on my fork to finish. The current fork contains the "atom" like version. You'd have to add an option to have a switch between the "atom" mode and the "plainState" mode. Sadly I have no free time to do so at the moment.

**Comment by Xuyuanp** [comment]
@0x00A I'm sorry I have no time to make this work be done. Maybe next month.

**Comment by alextrastero** [comment]
+1 (when ever you have time)

**Comment by honger05** [comment]
I think the icons appeared end of the filename not ahead of. will be better.

**Comment by sandrodz** [comment]
this would definitely be a great addition, looking forward.

**Comment by ismay** [comment]
Yeah this looks great. Do we even need the switch between atom and plainstate mode? I'm all for merging the current atom mode in the interest of moving this forward. Then a plainstate mode could always be added later if needed. Would prevent this pr from going stale.

**Comment by rawkode** [comment]
@robinfehr's fork works OK, but I'd love to see this progressed :smile:

**Comment by Aldlevine** [comment]
I've merged @robinfehr's fork into mine which (as of now) has no conflicts with the current master. I've submitted #79 for it. I didn't make any progress on handling the untracked files, but hopefully bringing it up to date will help to make things easier.

**Comment by tsony-tsonev** [comment]
Long time since the last comment here, but anyways. I [forked](https://github.com/tsony-tsonev/nerdtree-git-plugin) the latest version of this repo and used @robinfehr idea to enable custom file colors for different git statuses. So now we are able to use custom flags and custom colors for the file name based on the git status. We can also use just the one feature or the another or both of them. [vim-devicons](https://github.com/ryanoasis/vim-devicons) and [vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight) should be installed and the following minimal .vimrc config should be setup.

```
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:NERDTreeGitStatusNodeColorization = 1
let g:NERDTreeGitStatusWithFlags = 1

let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "⋆",            
    \ "Staged"    : "•",            
    \ "Untracked" : "∘",            
    \ "Dirty"     : "⁖",            
    \ "Clean"     : "✔︎",                   
    \ }

let g:NERDTreeColorMapCustom = {
    \ "Modified"  : "#528AB3",  
    \ "Staged"    : "#538B54",  
    \ "Untracked" : "#BE5849",  
    \ "Dirty"     : "#299999",  
    \ "Clean"     : "#87939A"   
    \ }  
```

![screenshot from 2018-11-22 17-24-44](https://user-images.githubusercontent.com/6035262/48911547-a4519c00-ee7b-11e8-9b60-3d853f790d2c.png)

Project is in golang which default filetype color from vim-nerdtree-syntax-highlight is yellow
The dirty directory containing modified file is in teal color
The modified file is in blue color
The staged file is in green color
The untracked file is in red color

I could not make the clean directory flag or color work (or any of the rest of the git statuses from the original version of the repo), but is not a big deal, because these are the most useful ones and they work.

**Comment by cocobear** [comment]
I like colored files.
@tsony-tsonev  can you make a PR and let @Xuyuanp merge it ?

**Comment by tsony-tsonev** [comment]
@cocobear I could, but I'm not sure if I would not introduce braking changes for the current users of the plugin, that's why I didn't do it in the first place. Also it is easier for me to maintain the functionality from my fork, because this repo does not seem to be very active. I already pushed a couple of things after reports from users. You can always clone my fork and see if it fits your needs.

**Comment by cocobear** [comment]
@tsony-tsonev Thanks for your reply. I will try it .

**Comment by cocobear** [comment]
Got this:
thanks @tsony-tsonev  i like it.

<img width="265" alt="screen shot 2019-01-29 at 12 40 17" src="https://user-images.githubusercontent.com/181942/51884695-55683b80-23c3-11e9-98fb-457a292623a1.png">

**Comment by R0LA1mRifcF8yAkk** [comment]
Any chance of reopening this issue? The fork has since been abandoned and the feature doesn't seem to be implemented in this project either.

**Comment by Xuyuanp** [comment]
@R0LA1mRifcF8yAkk wip

**Comment by izelnakri** [comment]
@Xuyuanp what is missing for implementing this feature? Could you also mention it in README.md? Maybe someone can help, started following this project for it. Unfortunately, I cant use this plugin without coloring, its more important showing icons next to my vim-devicons setup

**Comment by hrqmonteiro** [comment]
The fork who have the feature are currently not working, it breaks the Nerdtree. Any chance of this being implemented here? That looked like a cool feature.

**Comment by grech-ca** [comment]
Any update?

**Comment by spikespaz** [comment]
Bump, please, I hate the symbols
