### ISSUE TITLE
[nerdtree-git-status] option 'g:NERDTreeIndicatorMapCustom' is deprecated, please use 'g:NERDTreeGitStatusIndicatorMapCustom'

### ISSUE THREAD

**Issue by guiene** [Xuyuanp/nerdtree-git-plugin#154]
#### Self-Diagnosis

- [ ] I have searched the [issues](https://github.com/Xuyuanp/nerdtree-git-plugin/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation(README.md).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: 
- [ ] Vim/Neovim version `:echo v:version`: 
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 
- [ ] vimrc settings
    ```vim
    " all settings about nerdtree and other plugins
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only nerdtree-git-plugin installed.

#### Steps to Reproduce the Issue
1.

**Comment by Xuyuanp** [comment]
What's the point?

**Comment by Delayless** [comment]
In my vimrc, the problem is with vim-devicons
This plugin also use the variable `g:NERDTreeUpdateCursorHold` to cause this error.
If you really don't want to see this error message, you can add the followed in you vimrc.
```
autocmd VimEnter * unlet g:NERDTreeUpdateOnCursorHold
```
But the `vim-devicons`  **Updating On CursorHold** function maybe invalid(it's just a beauty plugyin).

By the way, why did you change the names of these variables? @Xuyuanp

**Comment by Xuyuanp** [comment]
Duplicate of #151
